[package]
name = "scu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
which = "4.4.0"
regex = "1"
whoami = "1.4.0"
